### ISSUE TITLE
cublas64预加载失败与cuDNN版本问题

### ISSUE THREAD

**Issue by yumo509** [AmusementClub/vs-mlrt#1]
请问压制过程出现这几行提示，是什么原因导致的？
在vsed上预览就没有任何报错信息
![image](https://user-images.githubusercontent.com/67351091/148658129-abab6eba-338a-45cd-95b4-89301511fe3f.png)

**Comment by WolframRhodium** [comment]
miniconda 里是不是有装 PyTorch？它有自带的 cublas 和 cudnn，可能会和 vs-mlrt 里带的冲突。可以试试在 vpy 里 `import vapoursynth` 之前加上这些代码:
```python3
import ctypes
ctypes.WinDLL(r"vs-mlrt 带的 cudnn 的路径")
ctypes.WinDLL(r"vs-mlrt 带的 cublas 的路径")
```

这些报错信息在 vsedit 是看不到的，如果用 https://github.com/Endilll/vapoursynth-preview 或 `python sakura.vpy` 的话应该能看到。

**Comment by AkarinVS** [comment]
另外，脚本里是否 import 了 pytorch（也可能是间接 import 的，比如使用了 PyTorch 的 vs-dpir）？或者 VS
路径的目录里是否包括其他使用了 cublas 和 cudnn 的滤镜？

从现象上看，看起来后者的概率更大一些。

一个可能的 workaround 是（如果准备用 vsmlrt 的话），执行 vspipe 之前清理一下 PATH 环境变量，将 miniconda
和 cuda SDK 的等包含其他版本的 cublas/cudnn DLL的路径去掉（代价是，VS 滤镜里面其他的依赖 cublas 和 cudnn
的滤镜就可能无法加载了。但是由于 NV 的 DLL 命名只包括主版本号，而 TensorRT
又严格要求相同的主/次版本号，这样的兼容性问题是没有可能完全解决的。。。）

**Comment by yumo509** [comment]
`import vapoursynth as vs
import mvsfunc as mvf
from vsrealesrgan import RealESRGAN

core = vs.get_core()

src8 = core.ffms2.Source(r"./sakura.VOB")
src32 = mvf.ToRGB(src8,depth=32)

ret=core.trt.Model(src32,engine_path=r"D:\realesrgan-xsx4.engine",tilesize=[720,480])

resize = ret = core.resize.Lanczos(ret, 1920,1080)
src162 = mvf.ToYUV(resize,depth=16,css="420")
src162.set_output()`

这是vpy里的内容

**Comment by yumo509** [comment]
> miniconda 里是不是有装 PyTorch？它有自带的 cublas 和 cudnn，可能会和 vs-mlrt 里带的冲突。可以试试在 vpy 里 `import vapoursynth` 之前加上这些代码:
> 
> ```python
> import ctypes
> ctypes.WinDLL(r"vs-mlrt 带的 cudnn 的路径")
> ctypes.WinDLL(r"vs-mlrt 带的 cublas 的路径")
> ```
> 
> 这些报错信息在 vsedit 是看不到的，如果用 https://github.com/Endilll/vapoursynth-preview 或 `python sakura.vpy` 的话应该能看到。

import ctypes
ctypes.WinDLL(r"D:\Miniconda3\vapoursynth64\plugins\vsmlrt-cuda\cublas64_11.dll")
ctypes.WinDLL(r"D:\Miniconda3\vapoursynth64\plugins\vsmlrt-cuda\cudnn64_8")

import vapoursynth as vs
import mvsfunc as mvf
from vsrealesrgan import RealESRGAN

core = vs.get_core()

src8 = core.ffms2.Source(r"./sakura.VOB")
src32 = mvf.ToRGB(src8,depth=32)

resize = ret = core.resize.Lanczos(ret, 1920,1080)
src162 = mvf.ToYUV(resize,depth=16,css="420")
src162.set_output()

载入dll后还是出现cudnn冲突，依旧提示TensorRT was linked against cuDNN 8.2.1 but loaded cuDNN 8.2.0

**Comment by yumo509** [comment]
> 

这是everything的搜索结果
![image](https://user-images.githubusercontent.com/67351091/148674180-8142d8ff-392c-4314-b708-f3a6f08ea583.png)

**Comment by WolframRhodium** [comment]
麻烦把
```python3
from vsrealesrgan import RealESRGAN
```
这行删了试试。如果没问题的话，ctypes 那些也可以删掉。

**Comment by yumo509** [comment]
> 麻烦把
> 
> ```python
> from vsrealesrgan import RealESRGAN
> ```
> 
> 这行删了试试。如果没问题的话，ctypes 那些也可以删掉。

我把这行
> from vsrealesrgan import RealESRGAN
删掉了，现在不提示cnn版本问题
ctypes 那两行是刚加上的，加上了就不会出现预加载cublas64失败问题。

**Comment by yumo509** [comment]
十分感谢各位的解答
