### ISSUE TITLE
可否增加rife v4.17 lite

### ISSUE THREAD

**Issue by Zhaodaidai** [AmusementClub/vs-mlrt#100]
可否增加rife v4.17 lite?

**Comment by WolframRhodium** [comment]
现在还没有这个模型，麻烦到 https://github.com/hzwer/Practical-RIFE 给作者提 issue

**Comment by Zhaodaidai** [comment]
好的谢谢

**Comment by WolframRhodium** [comment]
https://github.com/AmusementClub/vs-mlrt/commit/c9fe215c8bf570a24b3c43e5aa3cc39f140cc3a2

[`rife_v4.17_lite.7z`](https://github.com/AmusementClub/vs-mlrt/releases/download/external-models/rife_v4.17_lite.7z)

**Comment by Zhaodaidai** [comment]
收到收到 太感谢啦

**Comment by WolframRhodium** [comment]
RIFE 作者更辛苦
