### ISSUE TITLE
Rife v4.25 --> Rife v4.26 now available

### ISSUE THREAD

**Issue by netExtra** [AmusementClub/vs-mlrt#108]
Rife v4.25 was an improvement of the previous best v4.18. Rife v4.26 is meant to be the completion of v4.25 training and is now available. I know it's the weekend @WolframRhodium so I'm just going to leave this here and hope for the best :) If you can cool, if you can't cool. I will just have to learn to be more patient ;)

**Comment by WolframRhodium** [comment]
Sorry for my delayed operation, the model is available now.

Note that you may need to update vsmlrt.py for the v1 variant.

**Comment by netExtra** [comment]
> Sorry for my delayed operation, the model is available now.
> 
> Note that depending on the video resolution, you may need to update vsmlrt.py for the v1 variant.

Thanks I will have a look. SVP uses a helper script to automate engine model detection. So I might have to place your new code in there rather than the SVP version of vsmlrt.
