### ISSUE TITLE
Add downloads image to releases

### ISSUE THREAD

**Issue by flowreen** [AmusementClub/vs-mlrt#110]
Can u add a nice download number on each release tag like they have here:
https://github.com/shinchiro/mpv-winbuild-cmake/releases
on your releases page here?
https://github.com/AmusementClub/vs-mlrt/releases/

Cause it looks pretty simple:
https://img.shields.io/github/downloads/AmusementClub/vs-mlrt/v15.4/total?label=Downloads
Thanks!

**Comment by WolframRhodium** [comment]
Thank you four your suggestion! It has been added to the three latest releases.
