### ISSUE TITLE
v25 Heavy vs v25?

### ISSUE THREAD

**Issue by netExtra** [AmusementClub/vs-mlrt#115]
Hi

v25_heavy has a very large file size. Is there any advantage in using it. I tried it and didn't see any difference. What should I be looking out for?

**Comment by flowreen** [comment]
It's smooth AF 10/10

**Comment by netExtra** [comment]
> (Part of it is me, sorry. Previously v1 and v2 models shares the same weights, but starting with v4.25 lite I did another optimization on v2 models that break this equivalence. ~I'll port this optimization to v1 models later to fix the issue.~
> 
> Update: fixed by porting the optimization to v1 variants as well. The `v4.25_heavy.7z` archive uses a dictionary size of 128MB in compression, hope this won't cause too much of a problem.

some people using SVP say that the old v4.25 heavy works better than the new smaller one. In particular they say that the new version re-introduces some artefacts that were removed prior even to v4.25.

**Comment by WolframRhodium** [comment]
> Some people SVP users say that the old v4.25 heavy works better than the new smaller one. In particular they say that the new version re-introduces some artefacts that were removed prior even to v4.25.

Thanks, please give feedback directly to the RIFE author.

**Comment by hooke007** [comment]
v4.25 heavy was deleted/hidden.

**Comment by netExtra** [comment]
> v4.25 heavy was deleted/hidden.

I know a few SVP users who say that the old and very large 100MB "heavy" version is the smoothest Rife version yet but the 80MB version reintroduces artefacts that have already been fixed.

**Comment by hooke007** [comment]
I was talking about the official repo. It doesn't make sense to talk anything in other places.

**Comment by WolframRhodium** [comment]
> I know a few SVP users who say that the old and very large 100MB v4.25_heavy is the smoothest Rife version yet but the 80MB version reintroduces artefacts that have already been fixed.

The output should be identical.

**Comment by netExtra** [comment]
> > I know a few SVP users who say that the old and very large 100MB v4.25_heavy is the smoothest Rife version yet but the 80MB version reintroduces artefacts that have already been fixed.
> 
> The output should be identical.

SVP users are seeing more artefacts than even standard v4.25 had.

**Comment by netExtra** [comment]
> > I know a few SVP users who say that the old and very large 100MB v4.25_heavy is the smoothest Rife version yet but the 80MB version reintroduces artefacts that have already been fixed.
> 
> The output should be identical.

Yep. My mistake. Thanks.
