### ISSUE TITLE
First returned frame of ORT_DML backend is black

### ISSUE THREAD

**Issue by Mr-Z-2697** [AmusementClub/vs-mlrt#117]
Some models return error, but for the working models (e.g. RIFE and RealESRGAN), the first returned frame is all black, otherwise seem to be functional as expected.

OS: Windows 10 x64 22H2 (build 19045.2486)
Graphics card: RTX 4090
Driver version: 565.90

**Comment by WolframRhodium** [comment]
Thanks for the information, I have no time right now and will probably try to inspect the issue during the weekend.

**Comment by WolframRhodium** [comment]
Hi, thanks again and I can confirm the issue. It should be fixed in https://github.com/AmusementClub/vs-mlrt/commit/ac250539665e05471a3dc3b4cb78eadf5aca6ff7 and you can download the binary [here](https://github.com/AmusementClub/vs-mlrt/actions/runs/12094656121).

**Comment by Mr-Z-2697** [comment]
It works very well, thanks for the fix
