### ISSUE TITLE
Question: generating vapoursynth scripts without SVP

### ISSUE THREAD

**Issue by viennaontheline** [AmusementClub/vs-mlrt#118]
Sorry for weird question.
How to generate vapoursynth scripts without SVP?
I use mpv.
I need to genearte vapoursynth script from strings vsmlrt.py.
My preferences:
I have RTX 4070, I7-13700F, 32 GB DDR5 RAM, NVME
I need
TensorRT engine.
Interpolate video to 2x from original FPS.
RIFE 4.26 v2 model.
Max optimizations for RTX 4070 without degrading quality.

**Comment by WolframRhodium** [comment]
Hi, you may find [this](https://github.com/vadash/mpv-lazy-en) repository useful.
