### ISSUE TITLE
Update to CUDA 12, TensorRT 8.5.2, cuDNN 8.7.0

### ISSUE THREAD

**Issue by Jumaron** [AmusementClub/vs-mlrt#17]
Hi there,

first off great project!

I'am pretty sure your already aware of the updates and this is more ob a Bookmark/Reminder for when they get added, pretty sure no rael Code changes are needed.

Cheers

**Comment by WolframRhodium** [comment]
Hi!

Thanks for the reminder. cuDNN 8.7.0 does not officially support CUDA 12 in its [support matrix](https://docs.nvidia.com/deeplearning/cudnn/archives/cudnn-870/support-matrix/index.html#cudnn-cuda-hardware-versions) and we choose to follow the official guidance.

**Comment by Jumaron** [comment]
Very understandable, hope cuDNN 8.8.0 or 9.0.0 will come out soon, waiting for each other to update is always the worst, like with Pytorch and Phyton 3.11 ^^

I mean i can leave the issue open and rename it our can close it if you want.

**Comment by Jumaron** [comment]
cuDNN 8.8.0 is now officialy released with CUDA 12 support. [Support Matrix](https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html)

You guys rock btw!
Will close this Issue after the update.
I pray for a bit more Performance over this update ^^

**Comment by WolframRhodium** [comment]
TensorRT 8.5.3 still does not support CUDA 12. Peak performance is usually determined by TensorRT nowadays.

**Comment by Jumaron** [comment]
Your right i'am blind... hopefully they will adapt it soon

**Comment by Jumaron** [comment]
@WolframRhodium I think this can be soon closed as TensorRT 8.6 is released, waiting for final release Version. Any Performance increase on 30er NVIDIA Series?

**Comment by WolframRhodium** [comment]
No performance improvement observed so far.
