### ISSUE TITLE
could not generate dynamic engine

### ISSUE THREAD

**Issue by hooke007** [AmusementClub/vs-mlrt#20]
Based on https://github.com/AmusementClub/vs-mlrt/discussions/19#discussioncomment-4634619
I tried to use `static_shape=False` but failed.

[trtexec_230111_014402.log](https://github.com/AmusementClub/vs-mlrt/files/10388132/trtexec_230111_014402.log)

**Comment by WolframRhodium** [comment]
The log also suggests adding `--preview=fasterDynamicShapes0805` to https://github.com/AmusementClub/vs-mlrt/blob/e25cc7443ee0d8340cf5a11b926d2252cd28bfff/scripts/vsmlrt.py#L1083-L1090
, but I haven't test it.

**Comment by hooke007** [comment]
It seems `worksize=1024` is the lowest requirement in this case. Though I still observed many warning msg in the log, it could pass the benchmark. Increse this value to 2048 would be fine.

Could not make `fasterDynamicShapes0805` work here.
[trtexec_230111_031337.log](https://github.com/AmusementClub/vs-mlrt/files/10388572/trtexec_230111_031337.log)

**Comment by WolframRhodium** [comment]
> Could not make `fasterDynamicShapes0805` work here.

Sorry about that, it seems that `min_shapes=(0, 0)` should be blamed.

Please update `vsmlrt.py` and specify it manually (like `(64, 64)`). Performance improvement is significant here.

**Comment by hooke007** [comment]
Safely pass with `worksize=1024` and result is so close to static engine's perf.
Output 1000 frames in 13.19 seconds (75.83 fps)

**Comment by chainikdn** [comment]
> edit: `worksize=128` could work now.

model 4.4 do work, while 4.6 doesn't work even with 512
I'm trying with min 64*64 - max 3840*2176

**Comment by hooke007** [comment]
I have no idea, all looks good here...
[128.log](https://github.com/AmusementClub/vs-mlrt/files/10395307/128.log)

**Comment by chainikdn** [comment]
looks like 6G of device memory is not enough for model 4.6 with dynamic shapes
