### ISSUE TITLE
use `memPoolSize` instead?

### ISSUE THREAD

**Issue by hooke007** [AmusementClub/vs-mlrt#21]
Hi, I read this from the doc.

![Snipaste_2023-01-11_08-06-11](https://user-images.githubusercontent.com/41094733/211751665-6aaeb1d8-e44f-4124-8a20-999f892ca4f6.jpg)

I think we should use `memPoolSize` instead and allow users to set the value of option to None?

**Comment by AkarinVS** [comment]
The script already use the correct command line argument based on detected trt version.
https://github.com/AmusementClub/vs-mlrt/blob/949e703059325f59311a14f67cb460f4d506e8db/scripts/vsmlrt.py#L1056-L1059

**Comment by hooke007** [comment]
Sry my bad, but currently there is no way not to pass this flag in the wrapper, could you implement it?

**Comment by WolframRhodium** [comment]
*workspace

**Comment by hooke007** [comment]
If I don't add `workspace`, it is default back to 128.
`vapoursynth64/plugins\models\rife\rife_v4.6.onnx.1920x1088_fp16_workspace128_trt-8501_cudnn_I-fp16_O-fp16_NVIDIA-GeForce-RTX-4080_3dcbe72f.engine`

**Comment by WolframRhodium** [comment]
Done. Please check whether it affects performance. We experienced slower performance when using higher values of `workspace` before...

**Comment by hooke007** [comment]
LGTM.
For dynamic engine:
Comparing with `workspace=1024` (8.2/16Gib), `None` uses same VRAM and shows the similar speed (about 74FPS).
