### ISSUE TITLE
The speed of example in the release (pre) is much slower than the previous method.

### ISSUE THREAD

**Issue by hooke007** [AmusementClub/vs-mlrt#22]
> perform the necessary padding, YUV/RGB conversion and FP16 conversion in one go

https://github.com/AmusementClub/vs-mlrt/releases/tag/v13

In my device, "pad first and then crop" (283fps) is faster than "all-in-one" processing (243fps).

1080p_p10
<img src="https://user-images.githubusercontent.com/41094733/213198888-ef0ab4c5-8eae-4105-9880-00a5acb119ce.jpg" height=200>

2160p_p10
<img src="https://user-images.githubusercontent.com/41094733/213200600-d062f5de-85e5-4db6-888b-bbde6f0628f5.jpg" height=200>

**Comment by WolframRhodium** [comment]
Thanks, probably zimg does not efficiently fuse operations.

**Comment by hooke007** [comment]
@WolframRhodium Hi, i was testing rife v2(https://github.com/AmusementClub/vs-mlrt/commit/bd0ff9831e3b2ae377997d776fdf12c649dfb212) but failed. I'm not sure if I missed sth.

[trtexec_230227_151717.log](https://github.com/AmusementClub/vs-mlrt/files/10841166/trtexec_230227_151717.log)

**Comment by WolframRhodium** [comment]
Does it work if dynamic shapes or faster_dynamic_shapes is disabled? I only have tested the former.

**Comment by hooke007** [comment]
> faster_dynamic_shapes is disabled

Failed neither.

**Comment by WolframRhodium** [comment]
Hi, it seems that the `Range` operator does not support fp16 precision, and removing `--layerPrecisions=*:fp16 --layerOutputTypes=*:fp16 --precisionConstraints=obey` in your command will work. You may have to manually exclude those layers in precision specification.

**Comment by hooke007** [comment]
@WolframRhodium Hello, I have a question about v2 model.

For V1 model, I use 1920x 1088 as the value of opt_shape. Whether should I use the 1920x 1080 instead for V2?

**Comment by WolframRhodium** [comment]
I think 1920x1080 should be used for V2.
