### ISSUE TITLE
Silencing CUDA_MODULE_LOADING notifications for vstrt

### ISSUE THREAD

**Issue by Ironclad17** [AmusementClub/vs-mlrt#27]
I don't imagine enabling lazy loading would be possible, but is there a way to silence the notifications recommending it that fill up the log?

**Comment by Mr-Z-2697** [comment]
It's feasible actually, you'll need to put CUDA_MODULE_LOADING=LAZY in environment variables. I personally just add it to system settings for convenience, but you can use `set` command in cmd or os.environ in vpy as well. For trtexec though, you'll have to do some modification like https://github.com/Mr-Z-2697/vs-mlrt/commit/870c3043afb62eb2527d12895d9620d40f7ab02f , or maybe wait devs to add option.

**Comment by Ironclad17** [comment]
Have you done any benchmarks with it enabled? I'll try it out tonight.

**Comment by WolframRhodium** [comment]
Agree with @Mr-Z-2697. I haven't found any performance regression.

**Comment by Ironclad17** [comment]
I'm not so sure. I'm encoding videos with av1an, and the scene detection/chunking beforehand is taking 5x longer now. With the lower vram usage, I can run twice as many workers, but it will be faster to do the encoding in 2 steps. First scene detection without lazy cuda and only afterward enabling it. For future releases, I suggest writing it so that it can be enabled with a single line under the backend section.

**Comment by WolframRhodium** [comment]
What gpu are you using? Lazy loading usually saves vram by a few hundreds of megabytes, and it is a feature of nvidia driver whose behavior may varies between driver versions.

**Comment by Ironclad17** [comment]
An rtx 3080

**Comment by WolframRhodium** [comment]
Is there any performance improvement with >3 instances?

**Comment by Ironclad17** [comment]
I haven't had much time to test, but previously I was only able to run up to 4 instances with vram allocation ~6GB. Any higher and either av1an or the OS would crash reporting vram management errors. I've since switched to dynamic shapes, updated drivers,  and am now testing 6 instances with lazy cuda. The behavior is strange. While >6 instances will run now, cpu utilization decreases which likely means I'm just trading bottlenecks. If I stick to 6 instances the notification persists, vram and system memory allocation are 99%, cpu utilization is 100% but gpu utilization is significantly decreased, and I'm still not sure if it won't crash. My gpu is idling and power consumption has lowered from 180->77W.

**Comment by Ironclad17** [comment]
After much tinkering, I came to the conclusion that higher worker counts were actually bottlenecking no matter how I configured them. Best performance was with 3-4 workers with 6-8 threads/tiles which lead to the highest gpu utilization and power consumption. Even if multithreading is poor getting the frames to the gpu faster was ultimately much more important.

**Comment by Ironclad17** [comment]
I never did get this working. Even with the updates from https://github.com/Mr-Z-2697/vs-mlrt/commit/870c3043afb62eb2527d12895d9620d40f7ab02f , notification is still being being spammed while building the execution engine.

**Comment by WolframRhodium** [comment]
That should be a valid solution.

**Comment by Ironclad17** [comment]
I'm not sure what I overlooked.
[vsmlrt.txt](https://github.com/AmusementClub/vs-mlrt/files/12887619/vsmlrt.txt)

**Comment by WolframRhodium** [comment]
Then whether it is this file that is being loaded?

**Comment by Ironclad17** [comment]
That I'm positive of.

**Comment by WolframRhodium** [comment]
You should set your system environment variable. That one is only for engine building, not for loading.

**Comment by Ironclad17** [comment]
Sorry I have no idea where you could add that to the script. I don't see any equivalent lines in the inference sections.

**Comment by WolframRhodium** [comment]
At the top level, `os.environ["CUDA_MODULE_LOADING"] = "LAZY"`.

**Comment by Ironclad17** [comment]
`os.environ` only appears once in the script [prev_env_value = os.environ.get(env_key)](https://github.com/AmusementClub/vs-mlrt/blob/fd7ab34773f1a91715e67d9619f6d6759fe4708c/scripts/vsmlrt.py#L1286).
Should I replace that line with `prev_env_value = os.environ["CUDA_MODULE_LOADING"] = "LAZY".`

**Comment by WolframRhodium** [comment]
alternatively, you could modify it [system-wide](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html)

**Comment by Ironclad17** [comment]
Like this?
![like this](https://github.com/AmusementClub/vs-mlrt/assets/20147654/b78b6995-1022-47f8-904e-1bebfe1aa34a)

**Comment by WolframRhodium** [comment]
yep

**Comment by Ironclad17** [comment]
No luck. I am getting a new warning now.
`Creating lwi index file 100%
Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
INFO [av1an_core::context] resume was set but neither chunks.json nor done.json exist in temporary directory ".5166c39"
Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
INFO [av1an_core::context] Input: 1920x1080 @ 23.976 fps, YUV420P10, SDR
Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
Scene detection
00:00:00 ▐                                                                           ▌   0% 0/34046 (0 fps, eta unknown)Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading
00:00:01 ▐                                                                           ▌   0% 0/34046 (0 fps, eta unknown)Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading`

**Comment by Ironclad17** [comment]
Eureka that worked! Thank you so much.
