### ISSUE TITLE
guide to use vs-mlrt cuda with Real-CUGAN Pro

### ISSUE THREAD

**Issue by mrtaichi** [AmusementClub/vs-mlrt#28]
Hello I have experience using Real-CUGAN Pro with vapoursynth and ffmpeg in windows. However I do not understand how I can use vs-mlrt cuda with Real-CUGAN Pro vapoursynth (which will be finally be output in ffmpeg).

Just a sample vpy file with actual example would be very useful. 

I have a Nvidia GPU. So probably TensorRT would be the best option. isn't it? Please mention major installation steps. I am considering using vs-mlrt portable.

Can anyone please help? thanks.

**Comment by AkarinVS** [comment]
For installation, we recommend using the prebuilt VS portable from https://github.com/AmusementClub/tools/releases/latest/
(download `vapoursynth_portable_VERSION_cpu+cuda.7z`). It includes everything you need to use vs-mlrt and it's fully portable.

A sample vpy to use cugan-pro (`cugan.vpy`):
```python
import vapoursynth as vs
import vsmlrt
core = vs.core

src = core.lsmas.LWLibavSource(a)
rgb = core.resize.Bicubic(src, format=vs.RGBS)
rgb = core.akarin.Expr(rgb, "x 0 1 clamp")
flt = vsmlrt.CUGAN(rgb, noise=-1, scale=2, version=2, backend=vsmlrt.BackendV2.TRT())
res = core.resize.Bicubic(flt, format=src.format.id, matrix_s="709")
res.set_output()
```

You can use `vspipe -y cugan.vpy -a a="INPUT_VIDEO" - | ffmpeg -f yuv4mpegpipe -i pipe: ....` to encode the video.

Please refer to the [wiki](https://github.com/AmusementClub/vs-mlrt/wiki) for more information.

Please note that due to extremely limited bandwidth, we're not able to help you write VS scripts, so if you have questions regarding the sample vpy please use other forums. Thanks.

**Comment by mrtaichi** [comment]
Even if it is portable, can I just directly import vapoursynth & vsmlrt without installing them through python?
Does the cugan.vpy file needs to be placed to any specific location?

**Comment by ViRb3** [comment]
According to #31, we don't need to pre-clamp anymore, so the `rgb = core.akarin.Expr(rgb, "x 0 1 clamp")` line can be omitted.

**Comment by AkarinVS** [comment]
As mentioned in #31, I don't think we can safely say we can always remove the clamp for all cugan models/versions. It's safer to leave it as is. Debugging issues caused by out-of-range values can be very difficult.

**Comment by mrtaichi** [comment]
Hello. I am facing some problems.
1.  I could run with vspipe with both TRT & ORT. But it failed due to high memory usage. Could generate preview with vsedit.
2. I prefer to use vapoursynth enabled ffmpeg and that's what I tried later. But it shows the following error
`[vapoursynth @ 000001f6e94b3080] Failed to initialize VSScript (possibly PYTHONPATH not set).
	D:\Software\vs-mlrt\vapoursynth_portable_23H1b5p_cpu+cuda\CUGAN_TRT.vpy: Generic error in an external library`

- Is there a way to limit memory usage?
- The TRT method also takes like 10 minutes to go through some process before it can start/generate vsedit preview. what it does here? can it be skipped? ORT does not need this.
- Does the TRT & ORT method shows FPS of the process? Don't know from what I have seen or tried so far.

**Comment by WolframRhodium** [comment]
Hi, we need your script and ffmpeg command to understand what happens.

TRT has a large initialization overhead because it is trying and comparing different approaches to optimize the execution time. ORT is usually slower than TRT and uses more memory.

I'm not sure whether vs enabled ffmpeg can report execution time of each filter instance. That's available in vspipe's `--filter-time` option.

**Comment by mrtaichi** [comment]
When I used CUGAN through vspipe last year, the performance was too poor and memory usage was higher. But vs enabled ffmpeg gave much better results with perfect encodes.

Anyway, the above vs enabled ffmpeg issue is gone. As i expected ffmpeg itself is being used through system env var path & it is also using the vapoursynth that is installed on the system & not the one in the portable folder. Now it (vapoursynth) is showing missing module 'vsmlrt' , even though I copied the plugins & scripts from vapoursynth64 & VapourSynthScripts to appropriate system vapoursynth folders.

`[vapoursynth @ 0000012e757e3140] Failed to parse script: Python exception: No module named 'vsmlrt'

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2866, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2867, in vapoursynth._vpy_evaluate
  File "D:\Software\vs-mlrt\Test\CUGAN_TRT.vpy", line 2, in <module>
    import vsmlrt
ModuleNotFoundError: No module named 'vsmlrt'

D:\Software\vs-mlrt\Test\CUGAN_TRT.vpy: Generic error in an external library`

I think issue is vsmlrt module and any later dependencies have to be available globally in the system with proper links, since the portable folder resources and links are not working anymore. Do you have any idea? At least I can start by installing the vsmlrt module to python default module directory or something. But I dont know which files will go to which folder.

**Comment by AkarinVS** [comment]
you can put ffmpeg.exe (and its dependent DLLs) into the vs portable directory (i.e. the same directory where vspipe.exe is located,) and run it from there.

**Comment by mrtaichi** [comment]
@AkarinVS 
Hey it works just fine. Thanks.

Though for some files a colorspace error is shown
`Error on frame 0 request:
Resize error: Resize error 3074: no path between colorspaces (2/2/2 => 0/2/2). May need to specify additional colorspace parameters.`

The script is pretty much what you gave above. The same script worked for one file, but not for another.

**Comment by mrtaichi** [comment]
I have linked three 1 second video clips. 1 working (working.mkv) and two not working DBK-1s.mkv & DBX-2s.mkv. All three have different resolutions and no resize done.

Attached the vpy script file.
In the script, ORT_CUDA is used, since with this it is easy to generate preview in vsedit & observe the error.

[https://mega.nz/folder/bXJF3K6I#xe9kxeqvhRgd_QPAh8W7aw](url)

**Comment by WolframRhodium** [comment]
```python3
rgb = core.resize.Bicubic(src, format=vs.RGBS, matrix_in_s="709")
```

**Comment by mrtaichi** [comment]
It works. Thanks.

for some files, TRT initialization was choking on GPU memory & was repeatedly showing stuffs like this:
`[E] Error[1]: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::132] Error Code 1: Cuda Driver (invalid argument)
[W] [TRT] Requested amount of GPU memory (8589934592 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.`

Is there a way to limit memory usage?

**Comment by WolframRhodium** [comment]
tiling:
```python3
flt = vsmlrt.CUGAN(rgb, noise=-1, scale=2, version=2, backend=vsmlrt.BackendV2.TRT(fp16=True), tiles=(2, 2))
```

**Comment by NineMeowICT** [comment]
@WolframRhodium I'm sorry to bother you. A error is shown.
`Error: Failed to retrieve frame 1 with error: Resize error 1026: RGB color family cannot have YUV matrix coefficients
Output 4 frames in 0.72 seconds (5.57 fps)`
![image](https://github.com/AmusementClub/vs-mlrt/assets/115801669/c76bbe54-10e4-4d59-a6ae-d7348af7b8b3)

**Comment by WolframRhodium** [comment]
```python3
...
flt = core.std.SetFrameProp(flt, "_Matrix", intval=0) # new line
flt = core.resize.Bicubic(flt, format=src.format.id, matrix_s="709")
```
That is strange though.

**Comment by NineMeowICT** [comment]
> ```python
> ...
> flt = core.std.SetFrameProp(flt, "_Matrix", intval=0) # new line
> flt = core.resize.Bicubic(flt, format=src.format.id, matrix_s="709")
> ```
> 
> That is strange though.

Thanks! But the same error still appears.

**Comment by NineMeowICT** [comment]
The metadata of the source video:
`Input #0, matroska,webm, from 'G:\offline_anime_archived2\[ReinForce] Bleach (BDRip 720p x264 FLAC)\[ReinForce] Bleach (BDRip 720p x264 FLAC)\[ReinForce] Bleach - 001 (BDRip 960x720 x264 FLAC).mkv':
  Metadata:
    encoder         : libebml v1.3.3 + libmatroska v1.4.4
    creation_time   : 2016-07-20T11:11:24.000000Z
  Duration: 00:23:04.84, start: 0.000000, bitrate: 2634 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 960x720 [SAR 1:1 DAR 4:3], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS             : 1245747
      BPS-eng         : 1245747
      DURATION        : 00:23:04.467000000
      DURATION-eng    : 00:23:04.467000000
      NUMBER_OF_FRAMES: 33194
      NUMBER_OF_FRAMES-eng: 33194
      NUMBER_OF_BYTES : 215587114
      NUMBER_OF_BYTES-eng: 215587114
      _STATISTICS_WRITING_APP: mkvmerge v9.2.0 ('Photograph') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.2.0 ('Photograph') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-07-20 11:11:24
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-07-20 11:11:24
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(jpn): Audio: flac, 48000 Hz, stereo, s32 (24 bit) (default)
    Metadata:
      BPS             : 1387140
      BPS-eng         : 1387140
      DURATION        : 00:23:04.843000000
      DURATION-eng    : 00:23:04.843000000
      NUMBER_OF_FRAMES: 14426
      NUMBER_OF_FRAMES-eng: 14426
      NUMBER_OF_BYTES : 240121544
      NUMBER_OF_BYTES-eng: 240121544
      _STATISTICS_WRITING_APP: mkvmerge v9.2.0 ('Photograph') 64bit
      _STATISTICS_WRITING_APP-eng: mkvmerge v9.2.0 ('Photograph') 64bit
      _STATISTICS_WRITING_DATE_UTC: 2016-07-20 11:11:24
      _STATISTICS_WRITING_DATE_UTC-eng: 2016-07-20 11:11:24
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES`

**Comment by dtlnor** [comment]
@NineMeowICT you shouldn't re-assign the resized clip to src.

**Comment by NineMeowICT** [comment]
> @NineMeowICT you shouldn't re-assign the resized clip to src. you should name the rgb clip to rgb or something, rather than src.

Thanks! It works!

**Comment by NineMeowICT** [comment]
@WolframRhodium 
![image](https://github.com/AmusementClub/vs-mlrt/assets/115801669/a180216c-8af1-4f83-a537-dab645b7d720)
![image](https://github.com/AmusementClub/vs-mlrt/assets/115801669/e28300d1-deb0-40d5-b853-d72d1016ad18)
It stuck at the end for more than 1hr. Any ideas?

**Comment by WolframRhodium** [comment]
cmd should be used, powershell is known to be unreliable.

**Comment by NineMeowICT** [comment]
> cmd should be used, powershell is known to be unreliable.

Same as above. The process stuck at the end and the output file is empty. The video stream is supposed to be wrapped by a mkv wrapper under normal circumstances, but the wrapper isn't run.

**Comment by dtlnor** [comment]
@NineMeowICT may I have your cugan.py? it's hard to say what's happening without the script.

**Comment by NineMeowICT** [comment]
@dtlnor 
[cugan.txt](https://github.com/AmusementClub/vs-mlrt/files/13692712/cugan.txt)

**Comment by dtlnor** [comment]
@NineMeowICT  ummmm, your script and cmd did work on my enviroment, except that I change your OV_GPU backend to ORT_CUDA as I don't have a Intel gpu.
Maybe its better to open a new issue for your question.

**Comment by NineMeowICT** [comment]
@dtlnor Are you using the same version of FFmpeg?

**Comment by WolframRhodium** [comment]
We use x264 directly instead of ffmpeg. You may try `backend=Backend.OV_CPU()` or `ORT_CPU` first with `vspipe --end 99 ......` to test for only a few frames.

**Comment by NineMeowICT** [comment]
@WolframRhodium 
I tried `backend=Backend.OV_CPU()` and it outputed the video successfully.

**Comment by WolframRhodium** [comment]
Then it's unfortunate. Which GPU are you using?

**Comment by NineMeowICT** [comment]
> Then it's unfortunate. Which GPU are you using?

Intel ARC A770

**Comment by WolframRhodium** [comment]
With `vspipe cugan.py . -p -e 99` will it finish successfully?

**Comment by NineMeowICT** [comment]
> With `vspipe cugan.py . -p -e 99` will it finish successfully?

No. It still stuck at the end.
![image](https://github.com/AmusementClub/vs-mlrt/assets/115801669/1770133e-a923-41ae-b96e-60705736071c)

**Comment by WolframRhodium** [comment]
Please remove x264 for this test.

**Comment by NineMeowICT** [comment]
@WolframRhodium I ran ` vspipe -c y4m -p E:\some_software\vs-mlrt\test.py - > test.txt` and it can be finished successfully.
![image](https://github.com/AmusementClub/vs-mlrt/assets/115801669/c9780076-34ee-4de3-8d72-f14b7b5aee2d)

**Comment by NineMeowICT** [comment]
@WolframRhodium Oh! Sorry, I forgot to change the backend to OV_GPU just now.
![image](https://github.com/AmusementClub/vs-mlrt/assets/115801669/614bd147-1d15-46b4-9cad-3c9d601a5be2)

**Comment by NineMeowICT** [comment]
![image](https://github.com/AmusementClub/vs-mlrt/assets/115801669/e1c739bb-c1b1-43bc-9851-6effce26cc30)
![image](https://github.com/AmusementClub/vs-mlrt/assets/115801669/33567e88-f2ce-40cc-8efe-e36732e14255)
