### ISSUE TITLE
RealESRGAN models not working

### ISSUE THREAD

**Issue by mrtaichi** [AmusementClub/vs-mlrt#35]
I use the portable version. When using with TRT, among the RealESRGAN models, only animevideov3 works. Though even that does not work if "fp16=True" is set. The other two models animevideo_xsx2 and animevideo_xsx4 also do not work.

Here is the script I used:
`import vapoursynth as vs
core = vs.core
from vsmlrt import RealESRGANv2, RealESRGANv2Model, Backend
src = core.ffms2.Source(r"D\Test.mkv")
rgb = core.resize.Bicubic(src, format=vs.RGBS)
flt = RealESRGANv2(rgb, model=RealESRGANv2Model.animevideo_xsx2, backend=Backend.TRT())
res = core.resize.Bicubic(flt, format=src.format.id, matrix_s="709")
res.set_output() `

Error:
`[vapoursynth @ 000001acb7162f40] Failed to parse script: Python exception: trtexec execution fails, log has been written to C:\
Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2993, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2994, in vapoursynth._vpy_evaluate
  File "RK_S01E05-1m-40s_TRT-RealESR.vpy", line 10, in <module>
    flt = RealESRGANv2(rgb, model=RealESRGANv2Model.animevideo_xsx2, backend=Backend.TRT())`

Everything works with ORT_CUDA though.

**Comment by WolframRhodium** [comment]
Could you please provide the log?

**Comment by mrtaichi** [comment]
Hello I have provided two log files here. I have also added the error log part as well.
[https://mega.nz/folder/ra4VmbJB#vj983tAS1E3BiQOOqzBpKA](url)
One for regular TRT error & another for when fp16=True is used with animevideov3 model.

**Comment by AkarinVS** [comment]
Perhaps you can try executing the command in the first line of the log file in a cmd window and see if there are any other error not included in the log file?

e.g.
```batch
D:/Software/Multimedia/Video_Related/Ai_Up/vs-mlrt/vapoursynth_portable_23H1b5p_cpu+cuda/vapoursynth64/plugins\vsmlrt-cuda\trtexec --onnx=D:/Software/Multimedia/Video_Related/Ai_Up/vs-mlrt/vapoursynth_portable_23H1b5p_cpu+cuda/vapoursynth64/plugins\models\RealESRGANv2\RealESRGANv2-animevideo-xsx2.onnx --timingCacheFile=D:/Software/Multimedia/Video_Related/Ai_Up/vs-mlrt/vapoursynth_portable_23H1b5p_cpu+cuda/vapoursynth64/plugins\models\RealESRGANv2\RealESRGANv2-animevideo-xsx2.onnx.1920x1080_workspace128_trt-8501_cudnn_I-fp32_O-fp32_NVIDIA-GeForce-RTX-2060_328a7930.engine.cache --device=0 --saveEngine=D:/Software/Multimedia/Video_Related/Ai_Up/vs-mlrt/vapoursynth_portable_23H1b5p_cpu+cuda/vapoursynth64/plugins\models\RealESRGANv2\RealESRGANv2-animevideo-xsx2.onnx.1920x1080_workspace128_trt-8501_cudnn_I-fp32_O-fp32_NVIDIA-GeForce-RTX-2060_328a7930.engine --memPoolSize=workspace:128 --shapes=input:1x3x1080x1920 --tacticSources=-CUBLAS,-CUBLAS_LT --buildOnly --inputIOFormats=fp32:chw --outputIOFormats=fp32:chw
```

**Comment by mrtaichi** [comment]
Hello the log file is uploaded in the folder above with the name "3rd_log.txt".

**Comment by mrtaichi** [comment]
Yes, it silently exits.
the verbose_log file is uploaded.

**Comment by AkarinVS** [comment]
trtexec generates a path that is way too long for Windows to handle. You need to shorten the path to the portable directory.

`D:/Software/Multimedia/Video_Related/Ai_Up/vs-mlrt/vapoursynth_portable_23H1b5p_cpu+cuda/vapoursynth64/plugins\models\RealESRGANv2\RealESRGANv2-animevideo-xsx2.onnx.1920x1080_workspace128_trt-8501_cudnn_I-fp32_O-fp32_NVIDIA-GeForce-RTX-2060_328a7930.engine.cache.lock`.

For example, try make it `D:/Software/Multimedia/Video_Related/Ai_Up/vs-mlrt/23H1b5p_cuda`.

**Comment by mrtaichi** [comment]
that solved it.
on a different note,
backend=Backend.TRT() 
but in case of CUGAN BackendV2 is used. but ESRGAN can't use the v2. does that have an impact on performance or something?

**Comment by WolframRhodium** [comment]
why ESRGAN can't use the v2?

**Comment by mrtaichi** [comment]
`flt = RealESRGANv2(rgb, model=RealESRGANv2Model.animevideov3, backend=BackendV2.TRT(fp16=True), scale=2)`
If I use this, it says
`NameError: name 'BackendV2' is not defined`

**Comment by WolframRhodium** [comment]
```python3
from vsmlrt import BackendV2
```

**Comment by mrtaichi** [comment]
are there any models to be used in vsmlrt for real-world videos?
