### ISSUE TITLE
invalid input pixels with `scale=1` (waifu2x)

### ISSUE THREAD

**Issue by hooke007** [AmusementClub/vs-mlrt#37]
https://github.com/AmusementClub/vs-mlrt/blob/c4e5cb63c6879c3dfa03a34ca8b9485bdd24f5b3/scripts/vsmlrt.py#L339-L348

related https://github.com/AmusementClub/vs-mlrt/issues/32

**Comment by hooke007** [comment]
@WolframRhodium another similar issue

![Snipaste_2023-04-14_00-16-53](https://user-images.githubusercontent.com/41094733/231902974-1f22c830-0743-4791-959b-2dc6bfc03250.jpg)

**Comment by WolframRhodium** [comment]
Thanks!
