### ISSUE TITLE
Additional models

### ISSUE THREAD

**Issue by wiwaz** [AmusementClub/vs-mlrt#41]
Upstream waifu2x has "UpCUNET" and "VGG7" models, are there any plans for these models to be added to vs-mlrt?

**Comment by WolframRhodium** [comment]
These have been included in vsmlrt built-in models:
- `UpCUNet` corresponds to `vsmlrt.Waifu2xModel.cunet` models.
- `VGG7` corresponds to `vsmlrt.Waifu2xModel.upconv_7_anime_style_art_rgb` and `vsmlrt.Waifu2xModel.upconv_7_photo` models.

**Comment by wiwaz** [comment]
> UpCUNet corresponds to vsmlrt.Waifu2xModel.cunet models.
My understanding is that upcunet is an updated version of the old cunet with a new training dataset. Does this mean the "old" cunet model has been replaced entirely?

**Comment by WolframRhodium** [comment]
According to nagadomi, [`cunet/` and `upconv_7/` are converted from the original waifu2x pretrained model to pytorch](https://github.com/nagadomi/nunif/issues/6#issuecomment-1414582318).

**Comment by wiwaz** [comment]
I see, thank you

> I have also tried to train upconv_7 and upcunet with this repository and the latest dataset.
(These are not included in the release. Also, I have changed the code even in the last few days so it is not exactly the same.)

This comment made me think upcunet is using an updated dataset, but it appears i've misread the comment, apologies

**Comment by hooke007** [comment]
@WolframRhodium Any ideas to add the support of [AnimeJaNai v1](https://github.com/the-database/mpv-upscale-2x_animejanai/commit/8f051f8593058519cb576ee0758a1385740008e2) models(esrgan) into the mlrt wrapper?

**Comment by WolframRhodium** [comment]
Generally I would not support all models because of development efforts, but rather to provide a platform that allows other developers including you to use your favorite models efficiently. 

An appropriate wrapper could be `vsmlrt.inference()`, but certainly you may go deeper yourself (for int8 inference, for example).

**Comment by hooke007** [comment]
@WolframRhodium I just found upstream's 'upcunet' is more complex.
![Snipaste_2023-07-07_14-51-45](https://github.com/AmusementClub/vs-mlrt/assets/41094733/d0f1298c-9fcf-4c7c-8cf3-b0e0a70f3816)

Also, other models seems always to be changed each time (becoming more and more complex)

**Comment by WolframRhodium** [comment]
因为我做转换的时候会手动优化模型的，下图里很多常量节点都可以合并掉。trt 上可能优化效果不明显，它自己也一堆优化，但 ort/ncnn 这种没啥优化的框架上这种优化就有优势（ncnn 还没支持 shape 算子呢）。

**Comment by WolframRhodium** [comment]
另外 vs-mlrt 里的旧 waifu2x 模型是从 [这里](https://github.com/WolframRhodium/Super-Resolution-Zoo/tree/master/waifu2x/waifu2x-caffe%40lltcggie) 转过去的，和上游没关系。
