### ISSUE TITLE
Suggestion: Using VMAF for duplicated frame check

### ISSUE THREAD

**Issue by styler00dollar** [AmusementClub/vs-mlrt#5]
[VapourSynth-RIFE-ncnn-Vulkan](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-RIFE-ncnn-Vulkan) uses [VMAF](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-VMAF) to determine similarity of frames. The processing of similar frames can be skipped and result in a faster rendering process. In animation frames are often duplicated. I would really like to see that feature for [vstrt](https://github.com/AmusementClub/vs-mlrt/tree/master/vstrt). Or at least I would expect a performance increase with that.
```c++
if (sceneChange || psnrY >= d->skipThreshold) {
    dst = vsapi->copyFrame(src0, core);
```
But instead of copying the original, copying the last result so it is not needed to run a model on basically the same image again.

**Comment by AkarinVS** [comment]
There is no need to do it in the plugin.

We can easily implement it using FrameEval by selecting either the output
from the previous frame (basically the mlrt output shifted by -1 frame) or
the current frame based on the similarity metric of your choice of the
current source frame and the previous one.
This can be extended to support multiple duplicated frames as well.

I'd rather not bake such features into the plugins.

(Also note that the vs-trt backend is easily 4x faster than existing ncnn
based implementations, so even if you don't do such an optimization, vstrt
still performs faster.)

**Comment by WolframRhodium** [comment]
I agree with @AkarinVS and I think this routine should be implemented on top of vs-mlrt and benefits other filters as well

**Comment by 98mxr** [comment]
Even if you really need to compare similarities, it is recommended to use a more traditional measure like ssim

**Comment by AkarinVS** [comment]
The vstrt backend is so performant than even running very heavyweight
models like 1080p DPIR it's still faster than the encoder (unless you
aren't doing a fast encode, but then why bother using DPIR), so I really
don't see the need to skip processing similar frames and risk the
consequences.

That being said, if you really want this functionality, it's easy to
implement using Python and it could also benefit all spatial filters. I'm
inclined to close this issue as won't fix. Please feel free to reopen if
you have better reasons why this must be implemented in the plugins.

**Comment by LuisB79** [comment]
> There is no need to do it in the plugin. We can easily implement it using FrameEval by selecting either the output from the previous frame (basically the mlrt output shifted by -1 frame) or the current frame based on the similarity metric of your choice of the current source frame and the previous one. This can be extended to support multiple duplicated frames as well. I'd rather not bake such features into the plugins. (Also note that the vs-trt backend is easily 4x faster than existing ncnn based implementations, so even if you don't do such an optimization, vstrt still performs faster.) A bigger issue is that VMAF similarity (or any other similarity metric) does not work 100% reliable. Subtle differences in adjacent frames might be missed by the metric yet very noticeable by humans. Thus, choosing the right threshold becomes an art rather than exact science. You can certainly do the optimization yourself, but I don't think we should do it in the plugin as it might produce incorrect results if not used carefully, which is way worse than losing any potential speedups.

what about butteraugli?
