### ISSUE TITLE
Progress indication during .engine file creation?

### ISSUE THREAD

**Issue by Selur** [AmusementClub/vs-mlrt#52]
Would be nice if the .engine creation could output some progress indication,.. (to std::err)
When using  (vsmlrt.py and) HD content, I see for example:
```
Could not read timing cache from: F:/Hybrid/64bit/onnx_models/1x_Alias_200000_G.onnx.1440x1088_fp16_workspace1073741824_trt-8501_cudnn_I-fp32_O-fp32_NVIDIA-GeForce-RTX-4080_d3d7bd0.engine.cache. A new timing cache will be generated and written.
```
and then it can take ages, for the engine file to get created.
Would be nice so see some progress indication, to know that there is something going on without having to check the cpu/gpu usage to know that the process didn't die, but is still working.

**Comment by WolframRhodium** [comment]
```python3
Backend.TRT(verbose=True, ...)
```

**Comment by Selur** [comment]
Hmm,... using in vsedit/vsviewer just gives von large data blob,.
`clip = vsmlrt.inference([clip],network_path="F:/Hybrid/64bit/onnx_models/2x_UniScale_CartoonRestore-lite.onnx", backend=Backend.TRT(fp16=True, device_id=0,num_streams=1,verbose=True,use_cuda_graph=False, workspace=1 << 30))`
but using 'vspipe -i <path to script>' I see that these are tons of lines of output.
Any hint what of all those output could be interpreted as progress and just activity indication?

**Comment by WolframRhodium** [comment]
These are just activity indications, I don't know how to convert to progress indication.

**Comment by Selur** [comment]
Okay, thanks for the info. :)
