### ISSUE TITLE
Rife 4.7 better but still has weird artefacts

### ISSUE THREAD

**Issue by netExtra** [AmusementClub/vs-mlrt#57]
Rife artefacts are not regular but when they do occur they tend to be worse than other methods. Is there someone I can report particular artefacts to?

**Comment by Selur** [comment]
https://github.com/hzwer/Practical-RIFE is probably the right place to find help.

**Comment by netExtra** [comment]
> https://github.com/hzwer/Practical-RIFE is probably the right place to find help.

That sounds about right. I will open a case there. Thanks.
