### ISSUE TITLE
Rife has less artefacts but they are worse when they appear

### ISSUE THREAD

**Issue by netExtra** [AmusementClub/vs-mlrt#58]
When using SVP, Rife tends to have less artefacts than the other mode. I notice that Rife 4.7 has even less artefacts than 4.6. But the problem is that the artefacts that remain tend to be worse. Is there use to someone for me to point out the location of these artefacts ?

**Comment by WolframRhodium** [comment]
(you should open a issue at https://github.com/hzwer/Practical-RIFE

**Comment by netExtra** [comment]
> (you should open a issue at https://github.com/hzwer/Practical-RIFE

Sorry!  I kind of though I was already. Hopefully my dumb a** will get it right next time :)
