### ISSUE TITLE
Contributor models not loading

### ISSUE THREAD

**Issue by Ironclad17** [AmusementClub/vs-mlrt#62]
https://github.com/AmusementClub/vs-mlrt/blob/fd7ab34773f1a91715e67d9619f6d6759fe4708c/scripts/vsmlrt.py#L550
Something seems to be wrong with the pathing to the animejanai models. I notice it's organized differently than the ext-models for waifu2x for example.

**Comment by WolframRhodium** [comment]
This is an intended change as part of https://github.com/AmusementClub/vs-mlrt/pull/53

**Comment by Ironclad17** [comment]
Are the models supposed to renamed? As is
`rescale=RealESRGAN(src, model=RealESRGANModel(5007), backend=Backend.TRT(fp16=True, device_id=0, num_streams=2))`
or
`rescale=RealESRGAN(src, model=RealESRGANModel.animejanaiV2L3, backend=Backend.TRT(fp16=True, device_id=0, num_streams=2))`
Returns an error that the model isn't found.

**Comment by WolframRhodium** [comment]
You should download the new one in that PR. Of course you can still use the old one through renaming, but this is not suggested by that PR.

**Comment by Ironclad17** [comment]
No, no I'm using V2 already.

**Comment by WolframRhodium** [comment]
What's the error message?

**Comment by Ironclad17** [comment]
...and it's gone. I'm sorry must have been a typo somewhere on my end.
