### ISSUE TITLE
Could you please integrate EMA-VFI interpolation module?

### ISSUE THREAD

**Issue by zelenooki87** [AmusementClub/vs-mlrt#63]
[EMA-VFI]( https://github.com/MCG-NJU/EMA-VFI )
results are better than RIFE.
Thank you very much in advance!

**Comment by WolframRhodium** [comment]
I would at least wait until the toolchain (trt in particular) is mature before considering, otherwise it is simply too slow.

**Comment by zelenooki87** [comment]
again, please.?

**Comment by zelenooki87** [comment]
Please if it is doable.
Or shut down thread.
Thanks
