### ISSUE TITLE
[RIFE] v4.9 72% GPU [RIFE] v4.10 100% GPU Nvidia 4080

### ISSUE THREAD

**Issue by netExtra** [AmusementClub/vs-mlrt#68]
Hi
I'm currently peak at 74% using Rife 4.9 but with 4.10 I average 99% using SVP.  The last time I had a an issue like this I needed to update TRT dlls and exe on Windows. There doesn't seem to be any updated files this time.

**Comment by WolframRhodium** [comment]
What is the issue here?

**Comment by netExtra** [comment]
> What is the issue here?

Hi
The large increase in GPU usage. Rife 4.7 added about 30% over 4.6. Rife 4.9 reduced that to about 15-20%  over 4.6. Rife 4.10 doesn't seem to have any lesser artefacts than 4.9 but it still maxes out my GPU at 100%. 

I'm not complaining about the 100% because I can of course reduce what my GPU is doing. I was just surprised at the much larger GPU resource usage.

**Comment by netExtra** [comment]
> As mentioned in the [release](https://github.com/AmusementClub/vs-mlrt/releases/tag/v14.test2) page, these models are getting bigger and requires more computation resources. v4.7-v4.9 should have similar utilization, but it could be the case that TensorRT introduces some randomness in performance.

Thanks. The last time I had a similar issue I fixed it by updating the TRT DLL .EXE. files. This time there doesn't seem to be that option.

**Comment by netExtra** [comment]
> TensorRT 9.x does not improve performance of rife, FYI. They are working on other models.

Yes I tried that previously with 4.8 and if it did anything it was a little worse.

**Comment by netExtra** [comment]
I hope the v2 link gets updated for me to try. Thanks again.
