### ISSUE TITLE
Rife 4.11 minor artefact regression

### ISSUE THREAD

**Issue by netExtra** [AmusementClub/vs-mlrt#69]
Hi
Thank you for Rife 4.11. I am always happy a new model version is released. 

I found a slight regression for artefacts in one of my test files. There are a few more minor artefacts than in 4.9, very similar to Rife 4.6. But besides that it looks like it will behave similarly to Rife 4.10 for GPU usage. I guess in cutting down the file size something was lost.

**Comment by WolframRhodium** [comment]
Thanks, you should provide this kind of feedback to [the author](https://github.com/hzwer/Practical-RIFE) rather than here.

**Comment by netExtra** [comment]
I have never seen a regression in previous releases so this came as a surprise to me. It's only a minor one but it is there. For one of my test files it behaves like Rife 4.6.
