### ISSUE TITLE
InterpAny-Clearer comes with pro rife version, could you please implement?

### ISSUE THREAD

**Issue by zelenooki87** [AmusementClub/vs-mlrt#73]
Hi, great devs.
Could you please add support for model from this repo?
https://github.com/zzh-tech/InterpAny-Clearer
Thank you very much in advance

**Comment by zelenooki87** [comment]
I did not attend to be ironic or moron or to bother you....
That repo offers models for interpolation trained with more extra data.
Okay

**Comment by WolframRhodium** [comment]
Similar to the closure of https://github.com/AmusementClub/vs-mlrt/issues/63, this repository at present is not practical for use in encoding (although faster than EMA-VFI).
