### ISSUE TITLE
Mis-detected TensorRT version when using wrapper

### ISSUE THREAD

**Issue by banjaminicc** [AmusementClub/vs-mlrt#76]
Currently I'm testing the wrapper and vs-trt itself.
When running through the wrapper it seems to be detecting my tensorrt version as 8500
However if I run 
``
print(core.trt.Version()["tensorrt_version"].decode())
``
I obtain 8601
Are there any pointers to where the wrapper looks for dependencies? Because vs-trt itself is working with my pytorch setup but the vsmlrt wrapper is not

many thanks

**Comment by WolframRhodium** [comment]
https://github.com/AmusementClub/vs-mlrt/blob/4ec0edd6b7550d9b123771a83097a2f4da8e77cf/scripts/vsmlrt.py#L1357

**Comment by banjaminicc** [comment]
The odd thing is I am testing with the vsmlrt-cuda folder empty(I know it's not exactly recommended but it worked before)
So I am simply unsure where it is obtaining the tensorrt version
As even if I import the pytorch in the other script
``
from vsrife import RIFE
``
It detects the version as 8601

**Comment by banjaminicc** [comment]
Additionally if I build an engine with
``
VapourSynth/plugins64\vsmlrt-cuda\trtexec --onnx=VapourSynth/plugins64\models\rife\rife_v4.13_ensemble.onnx --timingCacheFile=VapourSynth/plugins64\models\rife\rife_v4.13_ensemble.onnx.min64x64_opt1376x736_max2560x2560_fp16_trt-8500_cudnn_I-fp16_O-fp16_NVIDIA-GeForce-RTX-3060_f2ea0d0.engine.cache --device=0 --saveEngine=VapourSynth/plugins64\models\rife\rife_v4.13_ensemble.onnx.min64x64_opt1376x736_max2560x2560_fp16_trt-8500_cudnn_I-fp16_O-fp16_NVIDIA-GeForce-RTX-3060_f2ea0d0.engine ....
``
(Which is the copy-pasted command from vsmlrt's error)
vsmlrt will fail to run the engine with a deserialization error which I believe points to a version mismatch

**Comment by WolframRhodium** [comment]
If you import vsrife, it imports the `tensorrt` python package [internally](https://github.com/HolyWu/vs-rife/blob/94efabb514651350541491151f4b1f6f4247493f/vsrife/__init__.py#L8), which in turn load the dll into the address space. When you call `core.trt.Version` later, it first looks for the dll in the address space and find a hit, then it will use that dll cache.

**Comment by WolframRhodium** [comment]
> vsmlrt will fail to run the engine with a deserialization error which I believe points to a version mismatch

There's nothing vsmlrt can do in this case (except for the advanced [version compatibility](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-861/developer-guide/index.html#version-compat) feature), because TensorRT itself requires you use a consistent library version.

**Comment by banjaminicc** [comment]
> If you import vsrife first, it imports the `tensorrt` python package [internally](https://github.com/HolyWu/vs-rife/blob/94efabb514651350541491151f4b1f6f4247493f/vsrife/__init__.py#L8), which in turn loads the dll into the address space. When you call `core.trt.Version` later, it first looks for the dll in the address space and find a hit, then it will use that dll cache.

This would be odd then because even without importing torch or vsrife, ``core.trt.Version`` returns 8.6.1

**Comment by WolframRhodium** [comment]
> with the vsmlrt-cuda folder empty

If this is true, it might find the dll in the `PATH` but I'm not sure.

**Comment by banjaminicc** [comment]
Thanks for all the pointers on dependency loading, I'll update if I understand the reason
Many thanks!

**Comment by banjaminicc** [comment]
Update : I have figured it out

The 8500 TensorRT version is from the Topaz Suite of Software lol
I was testing it and had it opened in the background and it sets its root directory (which contains some torch and tensorrt files) as PATH, which vsmlrt detected the files from.

So the simple solution was to close Topaz and Version 8601 could be detected
many thanks for the support
