### ISSUE TITLE
No module named 'onnx'

### ISSUE THREAD

**Issue by hooke007** [AmusementClub/vs-mlrt#8]
Hello, I got this error when I tried to use the script.
Here are more details.

I downloaded the file `vsmlrt-windows-x64-cuda.v12.7z` and Decompressed it.
Since the wiki haven't been updated, I tried to wade across the stream by feeling the way.

```
RIFE(clip=clip, backend=Backend.TRT())
```
It worked well. But if I added the param `scale=0.5,` , I would get the error msg: `No module named 'onnx'`

The full vpy:
```python
import vapoursynth as vs
from  vapoursynth import core
from vsmlrt import RIFE, RIFEModel, Backend

input = video_in
cut1 = input.resize.Bilinear(format=vs.RGBS, matrix_in_s="709")
cut2 = RIFE(clip=cut1, scale=0.5, model=RIFEModel.v4_6, backend=Backend.TRT())
cut3 = cut2.resize.Bilinear(format=vs.YUV420P8, matrix_s="709")
output = cut3.set_output()
```

**Comment by WolframRhodium** [comment]
`pip3 install onnx`

Some advanced features (like this one) require the onnx package. I have tried to minimise the use of onnx, even sacrificing performance in case of RIFE.

**Comment by hooke007** [comment]
Thanks. Maybe add some tips in the docs. I quickily check the script(vlmrt) and found some func need `numpy`.
