### ISSUE TITLE
Rife v4.14 "lite" version is heavier  than regular Rifev4.14

### ISSUE THREAD

**Issue by netExtra** [AmusementClub/vs-mlrt#81]
As the title says. My GPU usage is around 92-98% with Rife v4.15. GPU usage is locked at 100% with Rifev4.14 lite (v1 and v2).

**Comment by WolframRhodium** [comment]
As has already been said before, this kind of feedback is best reported to the author.

Unlike previous models, RIFE 4.14 lite model uses a kind of operation called group convolution, whose performance is usually limited by memory bandwidth rather than computational resources.

**Comment by netExtra** [comment]
So that would explain why I'm getting lots of Convolution tadtic errors I've never seen before.

**Comment by netExtra** [comment]
> As has already been said before, this kind of feedback is best reported to the author.
> 
> Unlike previous models, RIFE 4.14 lite model uses a kind of operation called grouped convolution, whose performance is usually limited by memory bandwidth rather than computational resources.

GPU memory bandwidth I assume?

**Comment by WolframRhodium** [comment]
Yes, GPU memory bandwidth.
