### ISSUE TITLE
vsmigx: failed to compile realesrgan onnx file

### ISSUE THREAD

**Issue by abihf** [AmusementClub/vs-mlrt#85]
I'm trying to run realesrgan on my RX 6800xt, but it always fail when running compile with same error:

```
# /usr/lib/vapoursynth/vsmlrt-hip/migraphx-driver compile --onnx /usr/lib/vapoursynth/models/RealESRGANv2/realesr-animevideov3.onnx --gpu --optimize --binary --output /usr/lib/vapoursynth/models/RealESRGANv2/realesr-animevideov3.onnx.1920x1088_fp16_fast_migx-2.8.0_AMD-Radeon-RX-6800-XT_cf94d81d.mxr --input-dim @input 1 3 1088 1920 --fp16
Compiling ... 
Reading: /usr/lib/vapoursynth/models/RealESRGANv2/realesr-animevideov3.onnx
terminate called after throwing an instance of 'migraphx::version_2_8_0::exception'
  what():  /long_pathname_so_that_rpms_can_package_the_debug_info/src/extlibs/AMDMIGraphX/src/include/migraphx/op/reshape_lazy.hpp:238: static_compute_shape: reshape_lazy on axis that is not packed.
Aborted (core dumped)
```

I have tried multiple model, but it always fail with same error.

I see you have successfully run realesrgan on RX 7900 (https://github.com/AmusementClub/vs-mlrt/releases/tag/v14.test3). May I know what realesrgan model do you use?

**Comment by WolframRhodium** [comment]
I've mentioned in the footnote that https://github.com/ROCm/AMDMIGraphX/commit/ecd5adc68e46b33146e37ae8e3897b73a901cc92 this specific version (or later) of migx is required.

**Comment by WolframRhodium** [comment]
You need to compile the code yourself before they make one (I think it might be two?) new release. It's pretty straightforward to follow the official instructions.

I think compiling MIGraphX takes me less than an hour, but since you are using a not officially supported GPU, I'm not sure whether you also need to compile MIOpen and rocBLAS.

**Comment by abihf** [comment]
Update: I can finally run animejanaiV3

```
# vspipe script.py -p /dev/null 
Script evaluation done in 0.34 seconds
Output 1000 frames in 48.43 seconds (20.65 fps)
```

**Comment by abihf** [comment]
Update 2: 20 fps is for fp16, but the output is only black screen.

If I disable fp16 it can only process 12 fps :disappointed:

**Comment by WolframRhodium** [comment]
That's sad. Have you set the `GPU_TARGETS` variable during compilation?

**Comment by abihf** [comment]
> Have you set the `GPU_TARGETS` variable during compilation?

Yup, I did. 

I will try to make [fp16 models](https://github.com/styler00dollar/VSGAN-tensorrt-docker/releases/tag/models) to run, but I need to to update vsmigx code because it requires `float` type as input and output.

For now, I still have quadro card that can process 11 fps.
