### ISSUE TITLE
When vstrt.dll fails to preload stuff the plugin crashes

### ISSUE THREAD

**Issue by YomikoR** [AmusementClub/vs-mlrt#9]
Ideally I should be able to see these errors in a previewer

**Comment by AkarinVS** [comment]
i've pushed a fix.
please see if this build https://github.com/AmusementClub/vs-mlrt/actions/runs/3477298918 fixes the issue for you.

now if preload fails, the whole plugin will skip registering the `trt` plugin namespace, so previewer should be able to report a nicer error (`No attribute with the name trt exists. Did you mistype a plugin namespace?`). And when the user runs the failing script in terminal, it should print out exactly which DLL fails to preload.

**Comment by YomikoR** [comment]
Thanks so much
