### ISSUE TITLE
.engine path location

### ISSUE THREAD

**Issue by Selur** [AmusementClub/vs-mlrt#90]
Would be nice if it would be possible to configure a folder where vs-mlrt puts .engine files.

**Comment by WolframRhodium** [comment]
Done via the `engine_folder` argument. Please use the wrapper file from the `trt-latest` branch for now. The master branch will be updated once the trt 10 GA is released.

**Comment by Selur** [comment]
Nice, thanks! Will try later (after work today)

**Comment by Selur** [comment]
Works fine. Thanks a lot!
