### ISSUE TITLE
Could you add support for Retinexformer? 

### ISSUE THREAD

**Issue by zelenooki87** [AmusementClub/vs-mlrt#99]
Original authors project page:
https://github.com/caiyuanhao1998/Retinexformer
Enhancement for low light situations and general image enhancement(FiveK model that work very well).
I have converted FiveK model to onnx to use with vsmlr onnx upscaler, but native implementation this repo and all models would be very nice.
thanks

**Comment by WolframRhodium** [comment]
No, because you can use your own onnx models.

**Comment by zelenooki87** [comment]
Okay, thanks
